import { describe,expect,it } from 'vitest';
import { buildOnboardingStep,validateEvidenceReference } from './realityOnboarding';
import type { EvidenceProbe } from './evidenceAcquisitionPlanner';

const probe:EvidenceProbe={subject:'AFFILIATE_ACCESS',dependencyTier:1,estimatedMinutes:3,capitalCostGbp:0,informationValue:100,accountRisk:0,instruction:'Verify Affiliate Center access and record status/reference.'};

describe('reality onboarding',()=>{
 it('turns the planner probe into an operator-specific step',()=>{
  const s=buildOnboardingStep(probe);
  expect(s.subject).toBe('AFFILIATE_ACCESS');
  expect(s.referenceHint).toContain('Affiliate Center');
 });
 it('requires a concrete evidence reference',()=>expect(()=>validateEvidenceReference(' ui ')).toThrow());
 it('rejects synthetic references previously generated by the UI',()=>expect(()=>validateEvidenceReference('operator-check:affiliate_access')).toThrow());
 it('normalizes a real safe reference',()=>expect(validateEvidenceReference(' Creator Center > Affiliate access ')).toBe('Creator Center > Affiliate access'));
});
