"""Brazil autonomous growth-engine durable truth."""
from alembic import op
import sqlalchemy as sa
revision='0006_growth_engine'
down_revision='0005_server_authority'
branch_labels=None
depends_on=None
def upgrade():
    op.create_table('growth_niches',sa.Column('niche_id',sa.String(100),primary_key=True),sa.Column('market',sa.String(2),nullable=False),sa.Column('language',sa.String(10),nullable=False),sa.Column('hypothesis',sa.Text(),nullable=False),sa.Column('trend_evidence',sa.Text(),nullable=False),sa.Column('production_cost_centavos',sa.Integer(),nullable=False),sa.Column('risk',sa.String(20),nullable=False),sa.Column('status',sa.String(20),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('growth_trends',sa.Column('trend_id',sa.String(100),primary_key=True),sa.Column('source',sa.String(40),nullable=False),sa.Column('source_ref',sa.String(1000),nullable=False),sa.Column('topic',sa.String(300),nullable=False),sa.Column('market',sa.String(2),nullable=False),sa.Column('language',sa.String(10),nullable=False),sa.Column('metrics_json',sa.Text(),nullable=False),sa.Column('evidence',sa.Text(),nullable=False),sa.Column('observed_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('growth_creatives',sa.Column('creative_id',sa.String(100),primary_key=True),sa.Column('niche_id',sa.String(100),sa.ForeignKey('growth_niches.niche_id'),nullable=False),sa.Column('trend_id',sa.String(100),sa.ForeignKey('growth_trends.trend_id'),nullable=False),sa.Column('experiment_id',sa.String(100),nullable=False,unique=True),sa.Column('plan_json',sa.Text(),nullable=False),sa.Column('evidence_ref',sa.String(1000),nullable=False),sa.Column('state',sa.String(30),nullable=False),sa.Column('media_ref',sa.String(1000)),sa.Column('media_hash',sa.String(64)),sa.Column('scheduled_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('growth_publication_intents',sa.Column('publication_intent_id',sa.String(100),primary_key=True),sa.Column('creative_id',sa.String(100),sa.ForeignKey('growth_creatives.creative_id'),nullable=False),sa.Column('idempotency_key',sa.String(100),nullable=False,unique=True),sa.Column('media_hash',sa.String(64),nullable=False),sa.Column('provider',sa.String(40),nullable=False),sa.Column('provider_publish_id',sa.String(300)),sa.Column('provider_status',sa.String(40),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('growth_follower_snapshots',sa.Column('snapshot_id',sa.String(100),primary_key=True),sa.Column('account_id',sa.String(200),nullable=False),sa.Column('followers',sa.Integer()),sa.Column('source',sa.String(40),nullable=False),sa.Column('evidence_ref',sa.String(1000),nullable=False),sa.Column('observed_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('growth_observations',sa.Column('observation_id',sa.String(100),primary_key=True),sa.Column('creative_id',sa.String(100),sa.ForeignKey('growth_creatives.creative_id'),nullable=False),sa.Column('views',sa.Integer()),sa.Column('likes',sa.Integer()),sa.Column('comments',sa.Integer()),sa.Column('shares',sa.Integer()),sa.Column('followers_before',sa.Integer()),sa.Column('followers_after',sa.Integer()),sa.Column('source',sa.String(40),nullable=False),sa.Column('evidence_ref',sa.String(1000),nullable=False),sa.Column('observed_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('growth_learning',sa.Column('learning_id',sa.String(100),primary_key=True),sa.Column('creative_id',sa.String(100),sa.ForeignKey('growth_creatives.creative_id'),nullable=False),sa.Column('verdict',sa.String(30),nullable=False),sa.Column('rationale',sa.Text(),nullable=False),sa.Column('next_mutation_json',sa.Text(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
def downgrade():
    for table in ['growth_learning','growth_observations','growth_follower_snapshots','growth_publication_intents','growth_creatives','growth_trends','growth_niches']: op.drop_table(table)
